# Generated by Django 6.0.5 on 2026-05-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavorazione',
            name='CODLAV',
            field=models.CharField(blank=True, max_length=20, verbose_name='Codice lavoro'),
        ),
    ]
