# Generated by Django 6.0.5 on 2026-06-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lavorazione_codlav'),
    ]

    operations = [
        migrations.AddField(
            model_name='artico',
            name='NOTROC',
            field=models.CharField(blank=True, max_length=50, verbose_name='Note rocca'),
        ),
        migrations.AddField(
            model_name='bagno',
            name='NOTROC',
            field=models.CharField(blank=True, max_length=50, verbose_name='Note rocca'),
        ),
        migrations.AlterField(
            model_name='artico',
            name='DESCRI',
            field=models.CharField(blank=True, max_length=50, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='artico',
            name='MATROC',
            field=models.IntegerField(blank=True, null=True, verbose_name='Matasse per rocca'),
        ),
        migrations.AlterField(
            model_name='artico',
            name='PEROFI',
            field=models.CharField(blank=True, max_length=10, verbose_name='Peso rocca finita'),
        ),
        migrations.AlterField(
            model_name='bagno',
            name='MATROC',
            field=models.IntegerField(blank=True, null=True, verbose_name='Matasse per rocca'),
        ),
        migrations.AlterField(
            model_name='bagno',
            name='PEROFI',
            field=models.CharField(blank=True, max_length=10, verbose_name='Peso rocca finita'),
        ),
        migrations.AlterField(
            model_name='disposizione',
            name='MATROC',
            field=models.IntegerField(blank=True, null=True, verbose_name='Matasse per rocca'),
        ),
        migrations.AlterField(
            model_name='disposizione',
            name='PEROFI',
            field=models.CharField(blank=True, max_length=10, verbose_name='Peso rocca finita'),
        ),
        migrations.AlterField(
            model_name='lavorazione',
            name='CODLAV',
            field=models.CharField(blank=True, max_length=40, verbose_name='Codice lavorazione'),
        ),
        migrations.AlterField(
            model_name='lavorazione',
            name='COLAFA',
            field=models.CharField(blank=True, max_length=3, verbose_name='Codice lavorazione Fadis'),
        ),
        migrations.AlterField(
            model_name='lavorazione',
            name='PASSAG',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Passaggio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lavorazione',
            name='QUAPRO',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Quantità prodotta'),
        ),
        migrations.AlterField(
            model_name='lavorazione',
            name='SCARTI',
            field=models.IntegerField(blank=True, null=True, verbose_name='Scarti (gr)'),
        ),
    ]
