# Generated by Django 6.0.5 on 2026-06-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_artico_notroc_bagno_notroc_alter_artico_descri_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagno',
            name='SPEDIT',
        ),
        migrations.AddField(
            model_name='bagno',
            name='QUAENT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Quantità in entrata'),
        ),
        migrations.AddField(
            model_name='bagno',
            name='QUAUSC',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Quantità in uscita'),
        ),
        migrations.AddField(
            model_name='lavorazione',
            name='TIPO',
            field=models.CharField(choices=[('D', 'Dipanatura'), ('R', 'Roccatura')], default='D', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='artico',
            name='TENSIO',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tensione'),
        ),
        migrations.AlterField(
            model_name='artico',
            name='TOLLER',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tolleranza'),
        ),
        migrations.AlterField(
            model_name='bagno',
            name='TENSIO',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tensione'),
        ),
        migrations.AlterField(
            model_name='bagno',
            name='TOLLER',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tolleranza'),
        ),
        migrations.AlterField(
            model_name='disposizione',
            name='TENSIO',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tensione'),
        ),
        migrations.AlterField(
            model_name='disposizione',
            name='TOLLER',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tolleranza'),
        ),
        migrations.AlterField(
            model_name='lavorazione',
            name='VELDIP',
            field=models.IntegerField(blank=True, null=True, verbose_name='Velocità'),
        ),
    ]
