# Generated by Django 6.0.5 on 2026-06-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_backfill_lavorazione_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artico',
            name='COLOR1',
        ),
        migrations.RemoveField(
            model_name='artico',
            name='COLORE',
        ),
        migrations.RemoveField(
            model_name='artico',
            name='CONDIP',
        ),
        migrations.RemoveField(
            model_name='artico',
            name='CONROC',
        ),
        migrations.RemoveField(
            model_name='bagno',
            name='CONDIP',
        ),
        migrations.RemoveField(
            model_name='bagno',
            name='CONROC',
        ),
        migrations.AddField(
            model_name='artico',
            name='CONI',
            field=models.CharField(blank=True, choices=[('C', 'Cartone cliente'), ('N', 'Cartone nostri'), ('P', 'Plastica'), ('R', 'Rotopress')], max_length=1, verbose_name='Coni'),
        ),
        migrations.AddField(
            model_name='bagno',
            name='COLOR1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Colore 2'),
        ),
        migrations.AddField(
            model_name='bagno',
            name='COLORE',
            field=models.CharField(blank=True, max_length=20, verbose_name='Colore'),
        ),
        migrations.AddField(
            model_name='bagno',
            name='CONI',
            field=models.CharField(blank=True, choices=[('C', 'Cartone cliente'), ('N', 'Cartone nostri'), ('P', 'Plastica'), ('R', 'Rotopress')], max_length=1, verbose_name='Coni'),
        ),
        migrations.AlterField(
            model_name='artico',
            name='COMPO1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Composizione 1'),
        ),
        migrations.AlterField(
            model_name='artico',
            name='COMPO2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Composizione 2'),
        ),
    ]
