# Generated by Django 6.0.5 on 2026-06-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_artico_color1_remove_artico_colore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artico',
            name='PARAFF',
            field=models.CharField(blank=True, choices=[('S', 'Sì'), ('N', 'No'), ('1', '1'), ('2', '2')], max_length=1, verbose_name='Paraffina'),
        ),
        migrations.AlterField(
            model_name='bagno',
            name='PARAFF',
            field=models.CharField(blank=True, choices=[('S', 'Sì'), ('N', 'No'), ('1', '1'), ('2', '2')], max_length=1, verbose_name='Paraffina'),
        ),
        migrations.AlterField(
            model_name='disposizione',
            name='PARAFF',
            field=models.CharField(blank=True, choices=[('S', 'Sì'), ('N', 'No'), ('1', '1'), ('2', '2')], max_length=1, verbose_name='Paraffina'),
        ),
        migrations.AlterField(
            model_name='lavorazione',
            name='TURNO',
            field=models.CharField(blank=True, choices=[('1', 'Turno 1'), ('2', 'Turno 2'), ('3', 'Turno 3')], max_length=1, verbose_name='Turno'),
        ),
    ]
