# Generated by Django 6.0.5 on 2026-06-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_artico_paraff_alter_bagno_paraff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavorazione',
            name='PESFR1',
            field=models.CharField(blank=True, max_length=40, verbose_name='Pesi fronte 1'),
        ),
        migrations.AddField(
            model_name='lavorazione',
            name='PESFR2',
            field=models.CharField(blank=True, max_length=40, verbose_name='Pesi fronte 2'),
        ),
    ]
