# Generated by Django 6.0.5 on 2026-06-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lavorazione_pesfr1_lavorazione_pesfr2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artico',
            name='ROCAUT',
        ),
        migrations.RemoveField(
            model_name='artico',
            name='STRROC',
        ),
        migrations.RemoveField(
            model_name='bagno',
            name='ROCAUT',
        ),
        migrations.RemoveField(
            model_name='bagno',
            name='STRROC',
        ),
        migrations.AddField(
            model_name='artico',
            name='DIPANA',
            field=models.BooleanField(default=False, verbose_name='Dipanato'),
        ),
        migrations.AddField(
            model_name='artico',
            name='ROCMAN',
            field=models.BooleanField(default=False, verbose_name='Rocca manuale'),
        ),
        migrations.AddField(
            model_name='artico',
            name='STRAUT',
            field=models.BooleanField(default=False, verbose_name='Stribbia automatica'),
        ),
        migrations.AddField(
            model_name='bagno',
            name='DIPANA',
            field=models.BooleanField(default=False, verbose_name='Dipanato'),
        ),
        migrations.AddField(
            model_name='bagno',
            name='ROCMAN',
            field=models.BooleanField(default=False, verbose_name='Rocca manuale'),
        ),
        migrations.AddField(
            model_name='bagno',
            name='STRAUT',
            field=models.BooleanField(default=False, verbose_name='Stribbia automatica'),
        ),
    ]
