# Generated by Django 6.0.5 on 2026-06-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_artico_rocaut_remove_artico_strroc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tipo',
            field=models.CharField(choices=[('D', 'Dipanatura'), ('R', 'Roccatura'), ('M', 'Magazzino')], max_length=1, verbose_name='Tipo operatore'),
        ),
    ]
