# Generated by Django 6.0.5 on 2026-06-26 19:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_userprofile_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artico',
            name='PENDING',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, db_column='PENDING', default=list),
        ),
        migrations.AddField(
            model_name='bagno',
            name='PENDING',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, db_column='PENDING', default=list),
        ),
        # Partial indexes so the daemon's "anything pending?" scan
        # (WHERE "PENDING" <> '{}') stays near-free when nothing is queued.
        migrations.RunSQL(
            sql='CREATE INDEX core_bagno_pending_idx ON core_bagno ((1)) WHERE "PENDING" <> \'{}\';',
            reverse_sql='DROP INDEX core_bagno_pending_idx;',
        ),
        migrations.RunSQL(
            sql='CREATE INDEX core_artico_pending_idx ON core_artico ((1)) WHERE "PENDING" <> \'{}\';',
            reverse_sql='DROP INDEX core_artico_pending_idx;',
        ),
    ]
