# Generated by Django 6.0.5 on 2026-06-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_artico_pending_bagno_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artico',
            name='CAMERA',
        ),
        migrations.RemoveField(
            model_name='bagno',
            name='CAMERA',
        ),
        migrations.RemoveField(
            model_name='disposizione',
            name='CAMERA',
        ),
    ]
