# Generated by Django 6.0.5 on 2026-06-26 00:00

from django.db import migrations, models


def merge_notes_forward(apps, schema_editor):
    """Join the three legacy note columns into the single NOTDR column."""
    Lavorazione = apps.get_model("core", "Lavorazione")
    for lav in Lavorazione.objects.all():
        joined = "\n".join(v for v in (lav.NOTDR1, lav.NOTDR2, lav.NOTDR3) if v)
        if joined:
            lav.NOTDR = joined
            lav.save(update_fields=["NOTDR"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_artico_camera_remove_bagno_camera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavorazione',
            name='NOTDR',
            field=models.TextField(blank=True, default='', verbose_name='Note'),
            preserve_default=False,
        ),
        migrations.RunPython(merge_notes_forward, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='lavorazione',
            name='NOTDR1',
        ),
        migrations.RemoveField(
            model_name='lavorazione',
            name='NOTDR2',
        ),
        migrations.RemoveField(
            model_name='lavorazione',
            name='NOTDR3',
        ),
        migrations.AddField(
            model_name='lavorazione',
            name='PESMAT',
            field=models.IntegerField(blank=True, null=True, verbose_name='Peso matasse'),
        ),
    ]
