# Generated by Django 6.0.5 on 2026-06-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_lavorazione_notdr_pesmat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavorazione',
            name='DIFETT',
            field=models.CharField(blank=True, max_length=255, verbose_name='Difetti'),
        ),
        migrations.AlterField(
            model_name='lavorazione',
            name='NOTDR',
            field=models.CharField(blank=True, max_length=255, verbose_name='Note'),
        ),
    ]
