# Generated by Django 6.0.5 on 2026-06-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pending_db_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artico',
            name='FONCON',
        ),
        migrations.RemoveField(
            model_name='bagno',
            name='FONCON',
        ),
    ]
