# Generated by Django 6.0.5 on 2026-06-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_artico_foncon_remove_bagno_foncon'),
    ]

    operations = [
        migrations.AddField(
            model_name='artico',
            name='CODLAV',
            field=models.CharField(blank=True, max_length=3, verbose_name='Codice lavorazione'),
        ),
        migrations.AddField(
            model_name='artico',
            name='COLAFA',
            field=models.CharField(blank=True, max_length=3, verbose_name='Codice lavorazione Fadis'),
        ),
        migrations.AddField(
            model_name='bagno',
            name='CODLAV',
            field=models.CharField(blank=True, max_length=3, verbose_name='Codice lavorazione'),
        ),
        migrations.AddField(
            model_name='bagno',
            name='COLAFA',
            field=models.CharField(blank=True, max_length=3, verbose_name='Codice lavorazione Fadis'),
        ),
    ]
