# Generated by Django 6.1 on 2026-09-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_pesroc_pesmat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tipo',
            field=models.CharField(choices=[('D', 'Dipanatura'), ('R', 'Roccatura'), ('M', 'Magazzino'), ('C', 'Camera')], max_length=1, verbose_name='Tipo operatore'),
        ),
    ]
